version: 2.1
workflows:
  bibframe2marc-xspec-tests:
    jobs:
      - build:
          context:
            - docker-hub-creds
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:scm
        auth:
          username: $DH_USERNAME
          password: $DH_PASSWORD
    steps:
      - checkout
      - run:
          name: Install prerequisites
          command: |
            sudo apt-get -q update && sudo apt-get install -qy build-essential cpanminus librdf-trine-perl librdf-query-perl libxml-libxslt-perl libmodule-build-perl libfile-share-perl xsltproc
            sudo cpanm MARC::Record MARC::File::XML
      - run:
          name: Run tests
          command: |
            git submodule init
            git submodule update
            perl Build.PL
            ./Build
            ./Build test
